In [ ]:
import numpy as np
import time

def ttaken(func):
  def wrapper(*args,**kwargs):
    start=time.time()
    res=func(*args,**kwargs)
    end=time.time()
    print(f'\ntime taken to capture arrays:{end-start:.4f}seconds\n')
    return res
  return wrapper

@ttaken
def array(inp):
  return np.array(list(map(float,(input(inp).split()))))

def basic_arithematic_function(a,b):
  print('addition:',np.add(a,b))
  print('subtraction:',a-b)
  print('multiplication:',a*b)
  try:
    print('divison:',a/b)
  except:
    print('Cannot divide by zero, please enter another number')
  print('power operation:',np.power(a,b))


def statistical_op(a,b):
  print('mean:',np.mean(a))
  print('median:',np.median(a))
  print('standard deviation not done')
  print('variance not done')
  print('minimum value:',np.min(a))
  print('maximum value:',np.max(a))
  print('Sum:',np.sum(a))
  print('product:',np.prod(a))#np np
  print('shape:',np.shape(a))
  print('size:',np.size(a))
  print('Data type:',a.dtype)

@ttaken
def _2dreshape(a):
  print('2D reshapes')
  size=np.size(a)
  _2d=[]
  for i in range(1,size+1):
      if size%i==0:
        row=i
        col=size//i
        _2d.append(a.reshape(row,col))
  print(*_2d,sep='\n\n')

@ttaken
def _3dreshape(a):
  print('\n3dReshape')
  size=np.size(a)
  _3d=[]
  for i in range(1,size+1):
    digit=size//i
    for j in range(1, digit+1):
      if digit%j==0:
        k=digit//j
        _3d.append(a.reshape(i,j,k))
    print(*_3d,sep='\n\n')

def array_manipulation(a,b):

  print(f"\nSorted:     {np.sort(a)}")
  print(f"Unique:     {np.unique(a)}")
  print(f"Val > Mean: {a[a > np.mean(a)]}")
  _2dreshape(a)
  _3dreshape(a)


def main():
  while True:
    try:
      arr1= array('Enter the array1 [seperated by space]:')
      arr2= array('Enter the array2 [seperated by space]:')
      if arr1.size!=arr2.size:
        print('both the array showuld have same size')
        continue

      print('='*40)
      print('Numpy Mathematical Calculator')
      print('='*40)
      print('\n1.Basic Arithmetic Operations\n2.Statistical Operations\n3.Array Manipulation\n4.Exit')
      print('='*40)
      try:
        choice=int(input('Enter the choice from the menu:'))

        if choice==1:
         basic_arithematic_function(arr1,arr2)

        elif choice==2:
         statistical_op(arr1,arr2)

        elif choice==3:
         array_manipulation(arr1,arr2)

        elif choice==4:
         break
      except ValueError:
        print('enter a valid input')
    except ValueError:
      print("Enter numerical values only")
main()




Enter the array1 [seperated by space]:1 2 3 4

time taken to capture arrays:6.8958seconds

Enter the array2 [seperated by space]:1 2 4 4

time taken to capture arrays:5.5767seconds

Numpy Mathematical Calculator

1.Basic Arithmetic Operations
2.Statistical Operations
3.Array Manipulation
4.Exit
Enter the choice from the menu:3

Sorted:     [1. 2. 3. 4.]
Unique:     [1. 2. 3. 4.]
Val > Mean: [3. 4.]
2D reshapes
[[1. 2. 3. 4.]]

[[1. 2.]
 [3. 4.]]

[[1.]
 [2.]
 [3.]
 [4.]]

time taken to capture arrays:0.0003seconds


3dReshape
[[[1. 2. 3. 4.]]]

[[[1. 2.]
  [3. 4.]]]

[[[1.]
  [2.]
  [3.]
  [4.]]]
[[[1. 2. 3. 4.]]]

[[[1. 2.]
  [3. 4.]]]

[[[1.]
  [2.]
  [3.]
  [4.]]]

[[[1. 2.]]

 [[3. 4.]]]

[[[1.]
  [2.]]

 [[3.]
  [4.]]]
enter a valid input


In [ ]:
1 2 3